version: '3.1'

services:
  wordpress:
    image: wordpress:4.4
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_pass
      WORDPRESS_DB_NAME: example_db
    volumes:
      - ./src:/var/www/html/wp-content/plugins
    networks:
        - wordpress

  db:
    image: mysql:8.0
    restart: always
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
        - wordpress

volumes:
  db:
networks:
  wordpress:
